In [1]:
a=[10,20,30,40]
type(a)

list

In [2]:
import numpy as np

In [6]:
a=np.array(a)

In [7]:
type(a)

numpy.ndarray

In [11]:
b=np.array([[1,2,3],[4,5,6]])
type(b)

numpy.ndarray

In [12]:
d=np.array([1,2,3,4,5])

In [13]:
d

array([1, 2, 3, 4, 5])

In [14]:
np.ndim(d)

1

In [15]:
e=np.array([[1,2,3,],[4,5,6]])

In [16]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.ndim(e)

2

In [20]:
f=np.array([[[1,2,3,],[4,5,6]],[[1,2,3],[4,5,6]]])

In [22]:
np.ndim(f)

3

In [23]:
e.shape

(2, 3)

In [24]:
f.shape

(2, 2, 3)

In [25]:
e.size

6

In [26]:
f.size

12

In [27]:
e.dtype

dtype('int64')

In [29]:
f.dtype

dtype('int64')

In [34]:
a1=np.arange(0,101)
a1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [35]:
a1=np.arange(0,101,2)
a1

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [46]:
a2=np.arange(21,72,2)
a2

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [45]:
a3=np.arange(22,71,2)
a3

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [48]:
a3=a3.astype("float")

In [49]:
a3.dtype

dtype('float64')

In [52]:
a4=np.linspace(1,200,10)
a4

array([  1.        ,  23.11111111,  45.22222222,  67.33333333,
        89.44444444, 111.55555556, 133.66666667, 155.77777778,
       177.88888889, 200.        ])

In [54]:
f

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [56]:
f[0][1][2]

np.int64(6)

In [57]:
f[0][0][2]

np.int64(3)